---
version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    volumes:
      - ./resources/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./secrets/rabbitmq-definitions.json:/run/secrets/rabbitmq-definitions.json
    ports:
      - 5673:5672
      - 15673:15672

  webserver:
    image: schulcloud/previewgenerator.webserver:latest
    build:
      context: .
      dockerfile: Dockerfile.webserver
    ports:
      - 8081:8080
    environment:
      ENV: production
      DEBUG: 'false'
      AUTH_USERPW: schulcloud:veryStrongPassword
      AMQP_URL: amqp://schulcloud:veryStrongPassword@rabbitmq/previewgenerator
    restart: always

  previewgenerator:
    image: schulcloud/previewgenerator:latest
    build:
      context: .
      dockerfile: Dockerfile.previewgenerator
    environment:
      ENV: production
      DEBUG: 'false'
      USE_CACHE: 'false'
      AMQP_URL: amqp://schulcloud:veryStrongPassword@rabbitmq/previewgenerator
    restart: always
